name: Refresh Profile Quote

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

# This grants the runner explicit permission to update your README
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Insert Random Quote
        uses: siddharth2016/quote-readme@main
