name: Refresh Profile Quote

on:
  # Runs automatically every day at midnight
  schedule:
    - cron: '0 0 * * *'
  # Allows you to manually trigger the update anytime
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Insert Random Quote
        uses: siddharth2016/quote-readme@v1.1.2
